# Using GPT-NeoX 20B as base
base_model: EleutherAI/gpt-neox-20b

# QLoRA config
load_in_4bit: true
bnb_4bit_compute_dtype: bfloat16
bnb_4bit_quant_type: nf4
bnb_4bit_use_double_quant: true

# LoRA adapter
adapter_type: lora
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
target_modules: ["query_key_value"]

# Data
datasets:
  - path: ./data/train.jsonl
    type: alpaca
val_set_size: 0.1

# Training
sequence_len: 1024
per_device_train_batch_size: 2
gradient_accumulation_steps: 16
num_train_epochs: 2
learning_rate: 2e-4
lr_scheduler: cosine
warmup_ratio: 0.03

# Misc
gradient_checkpointing: true
sample_packing: true
output_dir: ./outputs/neox20b-lora
logging_steps: 20
save_steps: 200
eval_steps: 200
